// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWEKOMKiVbNvXL1oX5kyGNUUrAT5DSnsI',
    appId: '1:357178289551:web:508d83d68295b851d86ffa',
    messagingSenderId: '357178289551',
    projectId: 'flutter-push-notificatio-c4077',
    authDomain: 'flutter-push-notificatio-c4077.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-c4077.appspot.com',
    measurementId: 'G-9W7P85ZZTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDP3GZnMPN838b9fgEUAt1zZKi9kyg2RM',
    appId: '1:357178289551:android:00b53e8beb913bc1d86ffa',
    messagingSenderId: '357178289551',
    projectId: 'flutter-push-notificatio-c4077',
    storageBucket: 'flutter-push-notificatio-c4077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4C7310kZSRulx7y0veGAJN-SoLRSIAmM',
    appId: '1:357178289551:ios:2ef2c4e316a28b52d86ffa',
    messagingSenderId: '357178289551',
    projectId: 'flutter-push-notificatio-c4077',
    storageBucket: 'flutter-push-notificatio-c4077.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4C7310kZSRulx7y0veGAJN-SoLRSIAmM',
    appId: '1:357178289551:ios:2ef2c4e316a28b52d86ffa',
    messagingSenderId: '357178289551',
    projectId: 'flutter-push-notificatio-c4077',
    storageBucket: 'flutter-push-notificatio-c4077.appspot.com',
    iosBundleId: 'com.example.pushNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWEKOMKiVbNvXL1oX5kyGNUUrAT5DSnsI',
    appId: '1:357178289551:web:4c3154391ca29358d86ffa',
    messagingSenderId: '357178289551',
    projectId: 'flutter-push-notificatio-c4077',
    authDomain: 'flutter-push-notificatio-c4077.firebaseapp.com',
    storageBucket: 'flutter-push-notificatio-c4077.appspot.com',
    measurementId: 'G-73QFVPJVWL',
  );
}
